import type { Experience } from '@/lib/content/schemas';

export const experience = [
  {
    slug: 'xposure-indonesia',
    company: 'Xposure Indonesia',
    companyLogo: {
      src: '/images/experience/xposure.webp',
      alt: 'Xposure Indonesia logo',
      width: 908,
      height: 395,
    },
    role: 'Full-Stack Developer',
    employmentType: 'Full-time',
    start: '2026-01',
    end: null,
    summary:
      'Developing data-intensive Customer Relationship Management work, legacy platform modernization, AI-assisted engineering workflows, and deployment standardization across multiple applications.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Architected the Customer Relationship Management data layer for more than 50,000 customer records with SQL query tuning, indexing, SQL views, and asynchronous job queues, reducing heavy-processing time by 40%.',
      'Modernized a legacy game-item sales platform into a full-stack architecture by simplifying front-end, back-end, database, and payment-integration flows, improving page performance by 45%.',
      'Designed an AI-assisted development workflow for a legacy Delphi retail management system using structured prompting, testing, build validation, and automated correction cycles, reducing implementation and debugging time by 20%.',
      'Standardized GitLab CI/CD, Docker deployment, and environment configuration across 10 applications, reducing manual deployment effort by 30% and improving release reliability.',
    ],
    relatedProjects: [],
    sourceNotes: [
      'Potential related project links should be added only after the matching case studies are verified and published.',
    ],
  },
  {
    slug: 'pt-kasir-pintar-internasional',
    company: 'PT Kasir Pintar Internasional',
    companyLogo: {
      src: '/images/experience/kasir-pintar.svg',
      alt: 'Kasir Pintar logo',
      width: 830,
      height: 218,
    },
    role: 'Front-End Developer',
    employmentType: 'Freelance',
    start: '2025-09',
    end: null,
    summary:
      'Building event-booking flows for customers and event organizers, with reusable interface patterns, session recovery, and front-end performance work across the booking experience.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Built a responsive event-booking platform serving more than 100 users by developing customer and organizer booking flows around reusable interface components.',
      'Implemented a session-recovery mechanism across the three-step booking process so expired sessions could be recovered without losing entered booking data.',
      'Improved Core Web Vitals and page performance by 20% through image optimization, lazy loading, dynamic imports, caching, and bundle monitoring.',
    ],
    relatedProjects: [],
  },
  {
    slug: 'pt-bank-rakyat-indonesia-persero-tbk',
    company: 'PT Bank Rakyat Indonesia (Persero) Tbk.',
    companyLogo: {
      src: '/images/experience/bri.svg',
      alt: 'BRI logo',
      width: 512,
      height: 260,
    },
    role: 'Front-End Developer',
    employmentType: 'Full-time',
    start: '2024-12',
    end: '2025-12',
    engagementContext: 'Under PT Orde Digital Intelektual',
    summary:
      'Supported QLola Cash Management Platform reliability work across multiple micro-frontends, with a focus on production-issue resolution, shared standards, bundle size, build footprint, and Web Application Firewall handling.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Supported production-issue resolution across QLola micro-frontends by applying shared engineering standards to the architecture, improving front-end reliability.',
      'Reduced remote bundle sizes and build-image footprints by 70% through front-end build and packaging improvements, making local development and deployment workflows lighter.',
      'Engineered Web Application Firewall (WAF) error-handling flows that surfaced blocked-request messages to users, improving troubleshooting visibility and reducing related support tickets by 30%.',
    ],
    relatedProjects: [],
  },
  {
    slug: 'central-bank-of-indonesia',
    company: 'Central Bank of Indonesia',
    companyLogo: {
      src: '/images/experience/bi.png',
      alt: 'Bank Indonesia logo',
      width: 2201,
      height: 697,
    },
    role: 'Full-Stack Developer Intern',
    employmentType: 'Internship',
    start: '2024-08',
    end: '2024-10',
    summary:
      'Designed and developed SI-SABI for the PSBI assistance program, connecting front-end, API, and PostgreSQL workflows for internal staff and beneficiaries.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Designed and developed the SI-SABI application for the PSBI assistance program with Next.js and PostgreSQL, improving administrative efficiency by 25% for internal staff and beneficiaries.',
      'Integrated front-end, API, and database workflows so assistance-program data could move through the application with clearer boundaries between user interface and persistence.',
      'Documented endpoints with Swagger and improved data-access performance by 15% through query optimization, selective data fetching, and clearer API response structures.',
    ],
    relatedProjects: [],
  },
  {
    slug: 'pilarmedia-indonesia',
    company: 'Pilarmedia Indonesia',
    companyLogo: {
      src: '/images/experience/pilarmedia.png',
      alt: 'Pilarmedia logo',
      width: 380,
      height: 107,
    },
    role: 'Front-End Developer',
    employmentType: 'Full-time',
    start: '2024-06',
    end: '2024-10',
    summary:
      'Developed front-end modules for a web-based logistics ERP, translating order, shipment, and operational workflows into reusable, consistent, data-oriented interfaces.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Developed logistics ERP front-end modules by translating order, shipment, and operational workflows into interfaces that supported data-intensive daily work.',
      'Designed reusable Material UI components and Redux state-management patterns across modules, reducing duplicated implementation patterns and improving interface consistency.',
      'Standardized REST API integration with asynchronous loading, success, and error states, reducing redundant request patterns and improving responsiveness across operational workflows.',
    ],
    relatedProjects: [],
    sourceNotes: [
      'Unverified module count, duplicated-code reduction percentage, and redundant-request reduction percentage were omitted from public copy.',
    ],
  },
  {
    slug: 'agile-product-based-learning',
    company: 'Agile Product-Based Learning',
    companyLogo: {
      src: '/images/experience/pens.png',
      alt: 'PENS logo',
      width: 391,
      height: 372,
    },
    role: 'Assistant Product Owner',
    employmentType: 'Full-time program',
    start: '2024-02',
    end: '2024-12',
    summary:
      'Guided the development team building Countlorie, a calorie-tracking platform using Flutter, Next.js, and Laravel, with emphasis on product direction and engineering maintainability.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Coached the development team while building Countlorie, aligning product guidance with Flutter, Next.js, and Laravel implementation work that increased user retention by 30% within three months after launch.',
      'Advocated DRY, KISS, YAGNI, and SOLID principles during product development, reducing codebase complexity by 25% without duplicating the project case study.',
      'Conducted continuous code reviews and refactoring sessions so maintainability and scalability concerns were handled during development instead of being deferred after launch.',
    ],
    relatedProjects: [],
  },
  {
    slug: 'data-polis',
    company: 'Data Polis',
    companyLogo: {
      src: '/images/experience/data-polis.png',
      alt: 'Data Polis logo',
      width: 512,
      height: 512,
    },
    role: 'Front-End Developer Intern',
    employmentType: 'Internship',
    start: '2023-05',
    end: '2024-06',
    summary:
      'Developed a responsive information system for the Association of Indonesian Insurance and Reinsurance Broker Experts (APARI), focusing on device accessibility, large dataset browsing, and reusable interface work.',
    contentStatus: 'published',
    verified: true,
    outcomes: [
      'Developed a responsive information system for the Association of Indonesian Insurance and Reinsurance Broker Experts (APARI), improving accessibility across devices and increasing user satisfaction by 20%.',
      'Implemented infinite scrolling for APARI datasets containing more than 3,000 records, reducing loading time by 40% during large-list browsing.',
      'Created reusable front-end components for repeated information-system patterns, reducing future development time by 15%.',
    ],
    relatedProjects: [],
  },
] satisfies Experience[];
