import type { Note } from '@/lib/content/schemas';

export const notes = [
  {
    title: 'Killing a process on a Linux port',
    slug: 'killing-process-linux-port',
    description: 'A short retrieval note for finding and stopping a process bound to a port.',
    publishedAt: '2026-07-07',
    updatedAt: '2026-07-07',
    lastTestedAt: '2026-07-07',
    contentStatus: 'draft',
    topics: ['Linux', 'Ops'],
    environment: ['TODO: Verify Linux distribution and shell.'],
    body: ['TODO: Add verified command sequence and expected output.'],
    expectedResult: 'TODO: Add expected terminal output.',
    caveat: 'TODO: Add safety caveat for killing processes.',
    references: [],
    relatedArticle: null,
  },
  {
    title: 'Fixing Laravel storage permissions',
    slug: 'fixing-laravel-storage-permissions',
    description: 'A compact note for diagnosing write failures in Laravel storage paths.',
    publishedAt: '2026-07-06',
    updatedAt: '2026-07-07',
    lastTestedAt: '2026-07-07',
    contentStatus: 'draft',
    topics: ['Laravel', 'Linux'],
    environment: ['TODO: Verify PHP and web server versions.'],
    body: ['TODO: Add verified ownership and permission commands.'],
    expectedResult: 'TODO: Add expected writable path result.',
    caveat: 'TODO: Add production permission caveat.',
    references: [],
    relatedArticle: null,
  },
  {
    title: 'Restarting Laravel queues',
    slug: 'restarting-laravel-queues',
    description: 'A note for safely restarting queue workers after deployment or config changes.',
    publishedAt: '2026-07-05',
    updatedAt: '2026-07-07',
    lastTestedAt: '2026-07-07',
    contentStatus: 'draft',
    topics: ['Laravel', 'Queues'],
    environment: ['TODO: Verify queue driver and process manager.'],
    body: ['TODO: Add verified queue restart steps.'],
    expectedResult: 'TODO: Add expected worker restart behavior.',
    caveat: 'TODO: Add caveat for long-running jobs.',
    references: [],
    relatedArticle: 'recovering-from-supervisor-worker-failures',
  },
  {
    title: 'Supervisor BACKOFF troubleshooting',
    slug: 'supervisor-backoff-troubleshooting',
    description: 'A retrieval note for diagnosing Supervisor BACKOFF without guessing.',
    publishedAt: '2026-07-04',
    updatedAt: '2026-07-07',
    lastTestedAt: '2026-07-07',
    contentStatus: 'draft',
    topics: ['Supervisor', 'Ops', 'Laravel'],
    environment: ['TODO: Verify Ubuntu and Supervisor versions.'],
    body: ['TODO: Add verified log paths, status commands, and common root causes.'],
    expectedResult: 'TODO: Add expected healthy Supervisor status.',
    caveat: 'TODO: Add caveat for repeatedly failing workers.',
    references: [],
    relatedArticle: 'recovering-from-supervisor-worker-failures',
  },
  {
    title: 'Nginx and PHP-FPM configuration',
    slug: 'nginx-php-fpm-configuration',
    description: 'A compact note for checking the handoff between Nginx and PHP-FPM.',
    publishedAt: '2026-07-03',
    updatedAt: '2026-07-07',
    lastTestedAt: '2026-07-07',
    contentStatus: 'draft',
    topics: ['Nginx', 'PHP-FPM', 'Ops'],
    environment: ['TODO: Verify Nginx, PHP-FPM, and operating system versions.'],
    body: ['TODO: Add verified config checks and reload commands.'],
    expectedResult: 'TODO: Add expected service status and response.',
    caveat: 'TODO: Add caveat for distribution-specific socket paths.',
    references: [],
    relatedArticle: 'deploying-laravel-with-gitlab-ci-cd',
  },
] satisfies Note[];
